### ISSUE TITLE
no proper credit

### ISSUE THREAD

**Issue by npxl32** [pandgum/neocities#1]
Give me and Tabtray proper credit not just "coding and ideas", also mention that you need a www for my site

As for "proper credit", I would like acknowledgements for making your opengraph preview, and bugfixing markup errors on the initial iteration of the site.

**Comment by npxl32** [comment]
Offtopic but maybe also remove the "tests" section? Those were for testing how much I can push the limits of Google Sites. By copy and pasting their code here you've broken your ENTIRE website's styling

**Comment by pandgum** [comment]
bet

**Comment by npxl32** [comment]
close the damn issue
